<script type="text/javascript" src="bootstrap/js/isotop.min.js"></script>
<link rel="stylesheet" type="text/css" href="css/slick.css"/>

<link rel="stylesheet" type="text/css" href="css/slick-theme.css"/>

<script type="text/javascript" src="bootstrap/js/slick.min.js"></script>

<link rel="stylesheet" type="text/css" href="owl/assets/owl.carousel.css">

<script type="text/javascript" src="owl/owl.carousel.js"></script>
<script type="text/javascript" src="bootstrap/js/script.js"></script>

<section class="container container-slide col-lg-10 col-lg-offset-1" style="width: 84%;">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">

      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="first-slide" src="images/slide-ben.jpg" alt="First slide">
        </div>
        <div class="item">
          <img class="second-slide" src="images/slide-ben.jpg" alt="Second slide">
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left glyphicon-left-modif" aria-hidden="true" ></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right glyphicon-right-modif" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
</section>
<section  class="container container-website col-lg-10 col-lg-offset-1">
	<div class="black-box col-lg-10 col-lg-offset-1">
		<div class="rub">
			<h3 class="col-lg-8 title-rub">MUSIQUE</h3>
			<h3 class="col-lg-4 ticket-rub"><span>+ DE MUSIQUE<span><img src="images/arrow.png" /></h3>
		</div>
	</div>
</section>
<section  class="container container-website col-lg-10 col-lg-offset-1">
	<div class="black-box col-lg-10 col-lg-offset-1">
		<div class="rub">
			<h3 class="col-lg-8 title-rub">EN VIDEO</h3>
			<h3 class="col-lg-4 ticket-rub"><span>+ DE VIDEOS<span><img src="images/arrow.png" /></h3>
		</div>
	</div>
</section>



		<!-- <div class="container marketing"><img src="images/shadow.png" width="95%"></div>
		<div class="container marketing box-white">
			<div class="row">
				<h3 style="margin: 30px 0px; margin-top: 60px;">
					<div class="title-back" ><span></span></div>
					<div class="title">QUI SOMMES NOUS?</div>
				</h3>
				<div class="row ligne">
				<div class="col-lg-6 left-col">
					<h3 style="text-align:left;">EN BREF</h3>
					<p style="margin-top: 30px; text-indent: 40px; text-align: justify;">Catalysis Events est une agence d’événementiel et de communication à votre écoute. Nous adoptons vis-à-vis de nos clients une démarche professionnelle pour offrir des prestations d’une grande qualité sur une large gamme de services et de produits publicitaires. Notre souci est votre satisfaction.</p>
				</div>
				<div class="col-lg-6 right-col">
					<iframe width="100%" height="315" src="https://www.youtube.com/embed/GkOypVjhgIM" frameborder="0" allowfullscreen></iframe>
				</div>
				</div>
			</div>
			<div class="row">
				<h3 style="margin: 60px 0px;">
					<div class="title-back" ><span></span></div>
					<div class="title">SERVICES & PRODUITS</div>
				</h3>
			 	<div class="row ligne">
		        	<div class="col-lg-3 col-md-6">
				        <a href="services#communication"><div class="img-circle" style="background-color: #222; width: 140px; margin: 0 auto; height: 140px;
						padding: 30px 26px;"><img  src="images/communication-icon.png" alt="Generic placeholder image"></div>
					    <h4>COMMUNICATION</h4></a>
				      	<p align="center" style="text-align: justify;">Nos &#233;quipes sont à votre disposition pour inventer les axes de votre communication et les d&#233;cliner sur le web ou sur supports papiers.</p>
		        	</div>
		        	<div class="col-lg-3 col-md-6">
				        <a href="services#evenementiel"><div class="img-circle" style="background-color: #222; width: 140px; margin: 0 auto; height: 140px;
						padding: 28px 29px;"><img  src="images/event-icon.png" alt="Generic placeholder image"></div>
					    <h4>EVENEMENTIEL</h4></a>
				      	<p align="center" style="text-align: justify;">Notre rôle est d’analyser tous les détails de votre problématique, de garantir l’accueil de vos participants dans les meilleures conditions, d’assurer une relation de proximité durant tout votre projet, et surtout de donner vie à la créativité de votre événement.</p>
		        	</div>
		        	<div class="col-lg-3 col-md-6">
				        <a href="services#print"><div class="img-circle" style="background-color: #222; width: 140px; margin: 0 auto; height: 140px;
						padding: 36px 30px;"><img  src="images/impression-icon.png" alt="Generic placeholder image"></div>
					    <h4>TRAVAUX D'IMPRESSION</h4></a>
				      	<p align="center" style="text-align: justify;">Nous mettons à disposition de nos clients plusieurs types d’impression: Offset, Numérique, Doming, Gaufrage, Gravage en laser, Sérigraphie, Transfert et la broderie. Nous nous occupons également de tous les types d’habillage et de mise en place de vos panneaux de chantier.</p>
		        	</div>
		        	<div class="col-lg-3 col-md-6">
				        <a href="services#prod"><div class="img-circle" style="background-color: #222; width: 140px; margin: 0 auto; height: 140px;
						padding: 30px 26px;"><img  src="images/produits-icon.png" alt="Generic placeholder image"></div>
					    <h4>PRODUITS</h4></a>
				      	<p align="center" style="text-align: justify;">La communication par objet est un phénomène qui nous touche quotidiennement ainsi nous mettons en place une capacite réelle à répondre à vos besoins en termes de supports promotionnels et de produits personnalisés.</p>
		        	</div>
		      	</div>
			</div> --> 
			<!-- <div class="row">
				<h3 style="margin: 60px 0px; margin-bottom: 40px;">
					<div class="title-back" ><span></span></div>
					<div class="title">DERNIERS TRAVAUX</div>
				</h3>
				<ul class="filters col-lg-8 col-lg-offset-2">
			      <li class="col-lg-2"><a class="is-checked" data-filter="*">MONTRER TOUT</a></li>
			      <li class="col-lg-2"><a class="" data-filter=".vid">COMMUNICATION</a></li>
			      <li class="col-lg-2"><a class="" data-filter=".art">événementiel</a></li>
			      <li class="col-lg-2"><a class="" data-filter=".art">TRAVAUX D'IMPRESSION</a></li>
			    </ul>

				<div class="col-lg-12 refs">
					<div class="grid-refs">
						<div class="ref-item col-lg-4 col-md-6 vid">
					        <a href="#"><div class="article"></div>
						    <h5>PRODUITS</h5></a>
					      	<h6 style="text-align: justify;">Communication</h6>
			        	</div>
			        	<div class="ref-item col-lg-4 col-md-6 vid">
					        <a href="#"><div class="article"></div>
						    <h5>PRODUITS</h5></a>
					      	<h6 style="text-align: justify;">Communication</h6>
			        	</div>
			        	<div class="ref-item col-lg-4 col-md-6 art">
					        <a href="#"><div class="article"></div>
						    <h5>PRODUITS</h5></a>
					      	<h6 style="text-align: justify;">Communication</h6>
			        	</div>
			        	<div class="ref-item col-lg-4 col-md-6 vid">
					        <a href="#"><div class="article"></div>
						    <h5>PRODUITS</h5></a>
					      	<h6 style="text-align: justify;">Communication</h6>
			        	</div>
			        	<div class="ref-item col-lg-4 col-md-6 art">
					        <a href="#"><div class="article"></div>
						    <h5>PRODUITS</h5></a>
					      	<h6 style="text-align: justify;">Communication</h6>
			        	</div>
			        	<div class="ref-item col-lg-4 col-md-6 vid">
					        <a href="#"><div class="article"></div>
						    <h5>PRODUITS</h5></a>
					      	<h6 style="text-align: justify;">Communication</h6>
			        	</div>
		        	</div>
				</div>
				<div style="clear: both" ></div>
			</div> 
		</div>
	</section>
	<section class="newsletter">
		<div class="container form-newsletter">
			<span class="col-lg-4 col-md-12 col-xs-12"><h4 style="font-size: 16px; font-weight: BOLD; color: white;">ABONNEZ-VOUS À NOTRE NEWSLETTER</h4></span>
			<span class="col-lg-6 col-md-8 col-xs-12"><input type="text" id="email" value="Entrez votre adresse email..."></span>
			<span class="col-lg-2 col-md-4 col-xs-12"><input type="button" id="abonner" value="S'ABONNER"></span>
		</div>
	</section>