<section  class="container container-website">
		<div class="container marketing"><img src="images/shadow.png" width="95%"></div>
		<div class="container marketing box-white">
			<div class="row">
				<h3 style="margin: 30px 0px; margin-top: 60px;">
					<div class="title-back" ><span></span></div>
					<div class="title">NOS SERVICES</div>
				</h3>
				<div class="row ligne" id="communication">
					<div class="col-lg-12">
						<img SrC="images/communication.png" width="100%" />
						<ul class="services">
							<p style="text-transform: uppercase;">Nos équipes sont à votre disposition pour inventer les axes de votre communication et les décliner sur le web ou sur supports papiers.</p>
							<p style="text-transform: uppercase;">Pour communiquer sur Internet :</p>
							<li><span>Conception ou adaptation de votre charte graphique.</span></li>
							<li><span>Webdesign et ergonomie de votre site Internet.</span></li>
							<li><span>Rédaction de vos pages web.</span></li>
							<li><span>Rédaction, illustration, montage et envoi de vos newsletters.</span></li>
							<li><span>Conception de bannières publicitaires.</span></li>
							<li><span>Animations interactives (HTML 5, Flash).</span></li>
							<li><span>Applications Android, iPhone et iPad.</span></li>
							<li><span>Communiquer sur Internet et au delà.</span></li>
							<li><span>Création de logo.</span></li>
							<li><span>Conception de charte graphique.</span></li>
							<li><span>Photo numérique (prises de vue, retouche, optimisation).</span></li>
							<li><span>Réalisation de vidéo (scénario, repérage, préparation, tournage, montage, optimisation).</span></li>
							<li><span>Conception d’affiche, dépliant, flyer, plaquette, rapport annuel, catalogue papier, …</span></li>
							<li><span>Rédaction de communiqués de presse.</span></li>
							<li><span>Campagne de Relations Presse.</span></li>
							<li><span>street marketing.</span></li>
						</ul>
					</div>	
				</div>
				<div class="row ligne" id="evenementiel">
					<div class="col-lg-12">
						<img SrC="images/events.png" width="100%"/>
						<ul class="services">
							<li><span>CONSEIL & CREATION</span></li>
							<p>Analyser tous les détails de votre problématique, établir clairement l'orientation stratégique sur laquelle nous basons nos recommandations. Mettre en valeur et en cohérence le contenu, les messages, et la forme de votre événement grâce à l'activation à plein régime des cellules grises de nos Creative Strategists (Conseil éditorial, Analyse et planning stratégique, Conception-rédaction, Direction artistique, Design et décoration.)</p>
							<li><span>LOGISTIQUE & VOYAGE</span></li>
							<p>Garantir l'accueil de vos participants dans les meilleures conditions, en toute sécurité, grâce à la maîtrise de tous les services d’accompagnement par nos experts en logistique : Transports, Hébergement, Restauration, Inscriptions, Dispositifs d'accueil, Conciergerie, Photographe, Tournage, etc. Et toujours tout anticiper, prévoir des plans B, C, D afin d’éviter tout écueil.</p>
							<li><span>MAITRISE DE PROJET</span></li>
							<p>Assurer une relation de proximité durant tout votre projet en vous dédiant un responsable de projet événementiel unique, garant de la réussite de votre événement : gestion des plannings, suivi budgétaire, contrôle de la qualité des opérations, des prestataires internes et externes, reporting et évaluation des résultat en fin de prestation.</p>
							<li><span style="text-transform: uppercase;">PRODUCTION TECHNIQUE SéCURITé</span></li>
							<p>Donner vie à la créativité de votre événement : rédaction du cahier des charges techniques ; gestion de la logistique pendant les phases de préparation coordination des différents prestataires techniques le jour J ; prise en charge de la relation avec les autorités et les administrations pour assurer la conformité de la sécurité.</p>
						</ul>
					</div>		
				</div>
				<div class="row ligne" id="print">
					<div class="col-lg-12">
						<img SrC="images/print.png" width="100%"/>
						<ul class="services">
							<li><span>Nos travaux d’impression</span></li>
							<p><b>-  OFFSET QUADRI :</b> Nous imprimons en quadrichromue suivant le procédé offset reconnu pour sa haute qualité de reproduction des écrits, images et illustrations. L’impression offset est préconisée pour la production du plus gros volume d’imprimés.</p>
							<p><b>-  IMPRESSION NUMERIQUE :</b> Nous traitons tous vos travaux d’impression numérique sur une presse digitale vous garantissant ainsi des impressions couleur avec des images d’une qualité exceptionnelle (qualité d’image à 400 x 2 400 dpi) et une excellente reproduction des lignes fines sur une gammes variée de formats et de grammages.</p>
							<p><b style="text-transform: uppercase;">-  Nous mettons aussi à disposition de nos clients d’autres types d’impression  :</b> doming, gaufrage, gravage en laser, sérigrapie, transfert et broderie.</p>
							<p><b style="text-transform: uppercase;" >-  Signalétique & panneaux de chantier :</b> Nous vous offrons des travaux de signalisation et de communication de vos chantiers grâce a nos moyens qui vous assurent un service de qualité (Palissade, Panneau de chantir, Signalétique plv, Bache tendue, Panneau pvc, Panneau bois...).</p>
							<p><b style="text-transform: uppercase;">-  Habillage de véhicules :</b> Nous mettons à votre disposition une équipe professionnelle de poseurs pour un habillage personnalisé de vos véhicules.</p>
						</ul>
						<img SrC="images/print1.jpg" width="100%"/>
					</div>		
				</div>
			</div>
			<div class="row" id="prod">
				<h3 style="margin: 30px 0px; margin-top: 60px;">
					<div class="title-back" ><span></span></div>
					<div class="title">NOS PRODUITS</div>
				</h3>
				<div class="row ligne" id="produits">
					<div class="col-lg-12 col-xs-12">
						<p style="text-indent: 20px; margin-bottom: 40px;">Parce que la communication par l’objet est un phénomène qui nous touche quotidiennement sans vraiment que nous nous en rendions compte, Catalysis Events a mis en place une capacité réelle à répondre à vos besoins en terme de supports promotionnels. Notre société a su développer un véritable savoir-faire dans le domaine du produit personnalisé.</p>
						<div class="col-lg-8 col-xs-12">
							<img SrC="images/brochures.jpg" width="100%"/>
						</div>
						<div class="col-lg-4 col-xs-12" style="text-align: left;">
							<ul class="produits">
								<li><span>Nos travaux d’impression</span></li>
								<li><span>CARTE VISITE</span></li>
								<li><span>CALENDRIER</span></li>
								<li><span>PAPIER A LETTRE</span></li>
								<li><span>ACCROCHE PORTE (HOTELLERIE)</span></li>
								<li><span>ENVELOPPE</span></li>
								<li><span>POCHETTE ET JACKETTE (POUR CD)</span></li>
								<li><span>CHEMISE A RABAT</span></li>
								<li><span>FLYER</span></li>
								<li><span>PLAQUETTE</span></li>
								<li><span>BROCHURE</span></li>
								<li><span>SAC</span></li>
								<li><span>SET DE TABLE</span></li>
								<li><span>BLOC NOTE</span></li>
								<li><span>EMBALLAGE CARTON</span></li>
								<li><span>STYLO EN METAL</span></li>
								<li><span>STYLO COMPTOIR</span></li>
								<li><span>PORTE CLEFS EN METAL</span></li>
								<li><span>PORTE CLEFS EN CUIR</span></li>
								<li><span>PARRURES</span></li>
								<li><span>COFRET</span></li>
								<li><span>CLE USB</span></li>
								<li><span>SOURIS ET TAPIS</span></li>
								<li><span>SOUS MAIN</span></li>
								<li><span>AGENDA</span></li>
								<li><span>CALCULATRICE</span></li>
								<li><span>PORTE CARTES VISITES</span></li>
								<li><span>SET DE BUREAU</span></li>
								<li><span>PORTE MONNAIE</span></li>
								<li><span>CONFERENCEIER CARTABLE</span></li>
								<li><span>CUBE ET POT</span></li>
								<li><span>MUG ET THERMO</span></li>
								<li><span>T-SHIRT</span></li>
								<li><span>CASQUETTE</span></li>
								<li><span>GILET</span></li>
								<li><span>TABLIER</span></li>
								<li><span>PARKA</span></li>
								<li><span>PORTE BADGE</span></li>
							</ul>
						</div>
					</div>		
				</div>
			</div>
			<div class="row">
				<div style="clear: both" ></div>
			</div>
		</div>
</section>

<script type="text/javascript">
	setTimeout(function() {
		if (document.location.hash != '')
		$(window).scrollTop($(window).scrollTop() - 120);
	}, 0)
	
</script>