<section  class="container container-website">
		<div class="container marketing"><img src="/images/shadow.png" width="95%"></div>
		<div class="container marketing box-white">
			<div class="row">
				<div class="ref-item col-lg-10 col-lg-offset-1 <?= $this->ref['cat'] ?>">
			        <div class="article col-lg-5">
			        	<img width="100%" height="266px" src="<?= $this->ref['img'] ?>" />
			        </div>
				    <div class="col-lg-5">
				    	<h5><?= $this->ref['title'] ?></h5>
			      		<h6 style="text-align: justify;"><?= $this->ref['cat'] ?></h6>
			      	</div>
			      	<div class="col-lg-12">
			      		<p><?= $this->ref['desc'] ?></p>
			      	</div>
				</div>
			</div> 
			</div>
			<div class="row">
				<div style="clear: both" ></div>
			</div>
		</div>
</section>