<script type="text/javascript" src="bootstrap/js/isotop.min.js"></script>
<section  class="container container-website">
		<div class="container marketing"><img src="images/shadow.png" width="95%"></div>
		<div class="container marketing box-white">
			<div class="row">
				<div class="row">
				<h3 style="margin: 60px 0px; margin-bottom: 40px;">
					<div class="title-back" ><span></span></div>
					<div class="title" style="text-transformer: uppercase;">nos références</div>
				</h3>
				<ul class="filters col-lg-8 col-md-12 col-lg-offset-2">
			      <li class="col-lg-2 col-md-3"><a class="is-checked" data-filter="*">MONTRER TOUT</a></li>
			      <li class="col-lg-2 col-md-3"><a class="" data-filter=".communication">COMMUNICATION</a></li>
			      <li class="col-lg-2 col-md-3"><a class="" data-filter=".evenementiel">événementiel</a></li>
			      <li class="col-lg-2 col-md-3"><a class="" data-filter=".impression">TRAVAUX D'IMPRESSION</a></li>
			    </ul>

				<div class="col-lg-12 refs">
					<div class="grid-refs">
						<?php foreach ($this->refs as $key => $ref) { ?>
							<!-- <div>
							<h1><?= $ref['title'] ?></h1>
							<p><?= $ref['desc'] ?></p>
							<img width="200px" src="<?= $ref['img'] ?>" />
							</div> -->
							<div class="ref-item col-lg-4 col-md-6 <?= $ref['cat'] ?>">
						        <a href="references/detail/id/<?= $ref['pid'] ?>"><div class="article"><img width="100%" height="266px" src="<?= $ref['img'] ?>" /></div>
							    <h5><?= $ref['title'] ?></h5></a>
						      	<h6 style="text-align: justify;"><?= $ref['cat'] ?></h6>
			        		</div>
						<?php } ?>
		        	</div>
				</div>
				<div style="clear: both" ></div>
			</div> 
			</div>
			<div class="row">
				<div style="clear: both" ></div>
			</div>
		</div>
</section>