<section  class="container container-website">
		<div class="container marketing"><img src="images/shadow.png" width="95%"></div>
		<div class="container marketing box-white">
			<div class="row">
				<h3 style="margin: 30px 0px; margin-top: 60px;">
					<div class="title-back" ><span></span></div>
					<div class="title">AUTHENTIFICATION</div>
				</h3>
				<div class="col-lg-8 col-lg-offset-2">
					
					<form id="contact-form" method="post" class="col-lg-12 form-contact" style="margin-top: 40px;"></span>
						<?php if(isset($this->loginfailed)) { ?>
						<div class="col-lg-12 alert alert-danger" role="alert"><?= $this->loginfailed ?></div>
						<?php } ?>
						<span class="col-lg-12"><input type="text" value="" name="user" value="Administrateur" ></span>
						<span class="col-lg-12"><input type="password" value="" name="pass" value="Mot de Passe" ></span>
						<span class="col-lg-12"><input type="hidden" value="1" name="completed" ></span> 
						<span class="col-lg-4 col-lg-offset-4"><input type="submit" value="Se connecter" ></span>
					</form> 
				</div>
			</div>
			<div class="row">
				<div style="clear: both" ></div>
			</div>
		</div>
</section>
