<html>
<head>
	<title>FATINE BENAGUIDA</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="viewport" content="initial-scale=1">
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="bootstrap/css/bootstrap.min.css">

	<!-- Optional theme -->
	<link rel="stylesheet" href="bootstrap/css/bootstrap-theme.min.css">

	<!-- Main Style -->
	

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
	<link href='http://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
	<!--<link href='http://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext' rel='stylesheet' type='text/css'> -->

	<!-- <link href='https://fonts.googleapis.com/css?family=Lato:400,700,300' rel='stylesheet' type='text/css'> -->

	<!-- Jquery -->
	<script src="bootstrap/js/jquery.min.js"></script>
	<script src="bootstrap/js/function.js"></script>
	<!-- Latest compiled and minified JavaScript -->
	<script src="bootstrap/js/bootstrap.min.js"></script>

	<script src="bootstrap/js/jquery.cycle.all.min.js"></script>
	<script src="bootstrap/js/jflickrfeed.min.js"></script>
	<script src="bootstrap/js/setup.js"></script>

	<link rel="shortcut icon" href="images/ico-fatin.png" type="image/x-icon"> 
	<link rel="stylesheet" href="css/style.css">
</head>
<body>
	<header>
		<nav class="col-lg-10 col-lg-offset-1 navbar navbar-default modif1">
	      <div class="container" style="width: 72%; margin: 0 auto;">
	        <div class="logo-title">
	        	<a href="/projects/fatine-blog/public/"><span style="font-family: BebasNeue;">FATINE BENAGUIDA</span></a>
	        </div>
	        <div class="navbar-header">
	          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
	            <span class="sr-only">Toggle navigation</span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	          </button> 
	        </div>
	        <div id="navbar" class="navbar-collapse collapse-in collapse">
	            <ul id="main-menu" class="nav navbar-nav " >
					<li class="<?= $this->home ?>"><a href="/projects/fatine-blog/public/">Accueil</a></li>
					<li class="<?= $this->about ?>"><a href="about">Biographie</a></li>
					<li class="<?= $this->discographie ?>"><a href="about">Discographie</a></li>
					<li class="parent <?= $this->services ?>">
						<a href="services">Galerie</a>
						<ul class="sub-menu">
							<li>
								<a class="parent" href="services"><i class="icon-file-alt"></i>Photos</a>
								<ul class="sub-menu">
									<li><a class="comm" href="services#communication">Radios</a></li>
									<li><a href="services#evenementiel">Festivals</a></li>
									<li><a href="services#print">Revues de presse</a></li>
									<li><a href="services#print">Divers</a></li>
								</ul>
							</li>
							<li><a href="services#prod"><i class="icon-wrench"></i>Vidéos</a></li>
						</ul>
					</li>
					<li><a href="references">Nos Réferences</a></li>
					<li class="<?= $this->contact ?>"><a href="contact">Contact</a></li>
				</ul>		
	        </div><!--/.nav-collapse -->
	      </div>
	    </nav>
	</header>
	<?php echo $this->layout()->content; ?>	
	<footer>
		<div class="copyright">
			<div class="container">
				<div class="row1-footer">
					<div class="col-lg-6 col-lg-offset-3">
						<p style="color: #000;">© 2015 fatine benaguida. TOUS DROITS RÉSERVÉS.&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;conçu par : MEDIA TUCH</p>
					</div>
				</div>			
			</div>
		</div>
	</footer>

</body>
</html>

