<!-- <section  class="container container-website">
		<div class="container marketing"><img src="images/shadow.png" width="95%" id="top"></div>
		<div class="container marketing box-white">
			<div class="row">
				<h3 style="margin: 30px 0px; margin-top: 60px;">
					<div class="title-back" ><span></span></div>
					<div class="title">NOS COORDONNEES?</div>
				</h3>
				<div class="row ligne">
		        	<div class="col-lg-4 col-md-4 col-xs-12 coord">
				        <div class="img-circle" style="background-color: #de156c; width: 140px; margin: 0 auto; height: 140px;
						padding: 30px 26px;"><i class="fa fa-map-marker" style="font-size: 60px; margin: 10px auto; color: white;"></i></div>
					    <h4>SIÈGE SOCIAL</h4>
				      	<p style="text-align: center; color: #999;">24 Rue Telemcen,<br>V.N CP 50010, Meknes, MAROC</p>
		        	</div>
		        	<div class="col-lg-4 col-md-4 col-xs-12 coord">
				        <div class="img-circle" style="background-color: #de156c; width: 140px; margin: 0 auto; height: 140px;
						padding: 30px 26px;"><i class="fa fa-phone" style="font-size: 60px; margin: 10px auto; color: white;"></i></div>
					    <h4>APPELEZ NOUS</h4>
				      	<p style="text-align: center; color: #999;">+212 6 14 81 39 53</p>
		        	</div>
		        	<div class="col-lg-4  col-md-4 col-xs-12 coord">
				        <div class="img-circle" style="background-color: #de156c; width: 140px; margin: 0 auto; height: 140px;
						padding: 30px 26px;"><i class="fa fa-envelope" style="font-size: 60px; margin: 10px auto; color: white;"></i></div>
					    <h4>ENVOYEZ UN EMAIL</h4>
				      	<p style="text-align: center; color: #999;">Contact@catalysis-events.com</p>
		        	</div>
		        </div>
		        <div class="row ligne">
		          	<div class="col-lg-8 col-md-12 register col-lg-offset-2" >
			      		<div class="col-lg-3 col-md-3"><span>N° RC :</span> 37193</div>
			      		<div class="col-lg-3 col-md-3"><span>N° de patente :</span> 62295273</div>
			      		<div class="col-lg-3 col-md-3"><span>N° identifiant fiscal :</span> 151664267</div>
			      		<div class="col-lg-3 col-md-3"><span>N° affiliation à la CNSS :</span> 9934622</div>
			      	</div>
			    </div>
			    <div class="row ligne">
			      	<div class="col-lg-12">
			      		<div style="text-decoration:none; overflow:hidden; height:500px; width:100%; max-width:100%;"><div id="google-maps-canvas" style="height:500px; width:100%;max-width:100%;"><iframe style="height:500px;width:100%;border:0;" frameborder="0" src="https://www.google.com/maps/embed/v1/place?q=Catalysis+Events,+Meknès,+Maroc&key=AIzaSyAN0om9mFmy1QN6Wf54tXAowK4eT0ZUPrU"></iframe></div><a class="google-html" rel="nofollow" href="https://www.treat-lice.com/what-are-head-lice/" id="grab-map-authorization">What are head lice?</a><style>#google-maps-canvas img{max-width:none!important;background:none!important;font-size: inherit;}</style></div>
			      	</div>
		      	</div>
			</div>
			<div class="row">
				<h3 style="margin: 30px 0px; margin-top: 60px;">
					<div class="title-back" ><span></span></div>
					<div class="title">CONTACTEZ-NOUS</div>
				</h3>
				<div class="row ligne">
		        	<form id="contact-form" class="col-lg-12 form-contact" enctype="multipart/form-data">
				        <span class="col-lg-6"><input type="text" id="nom" value="Nom (Obligatoire)" name="name" ></span>
				        <span class="col-lg-6"><input type="text" id="mail" value="Email (Obligatoire)" name="email"></span>
				        <span class="col-lg-6">
				        	<input type="text" id="objet" value="Objet" name="subject">
						</span>
				        <span class="col-lg-6">
				        	<input id="uploadfile" type="file" name="file" />
				        </span>
				        <span class="col-lg-12"><textarea autofocus rows="10" name="message">Votre Message (Obligatoire)
						</textarea></span>
						<span class="col-lg-12">
							<span class="col-lg-4  col-md-4 col-lg-offset-4 col-md-offset-4"><input type="submit" id="submit" value="ENVOYER LE MESSAGE" /></span>
						</span>
		        	</form>

			         <script>
			         	$('#contact-form').submit(function(e) {
						  e.preventDefault();
						  e.stopPropagation();
						  var self = $(this);
						  var file = new FormData($(this)[0]);
						  file.append('file', $("#uploadfile")[0].files);
						  $.ajax({
						    type: "POST",
						    url: 'contact/contactme',
						    data: file,
						    cache: false,
						    contentType: false,
						    processData: false,
						    success: function(response) {
						    	$('#contact-form')[0].reset();
						    	$('.modal').modal('show');
						   	}
						  });

						  return false;
						 });
			         </script>

		        </div>
			</div>
			<div class="row">
				<div style="clear: both" ></div>
			</div>
		</div>
</section>

<div class="modal fade bs-example-modal-sm in" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" >
	<div class="modal-dialog modal-sm">
	  <div class="modal-content">
	    <div class="modal-header">
	      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
	      <h4 class="modal-title" id="mySmallModalLabel">Message</h4>
	    </div>
	    <div class="modal-body">
	      Votre message a été bien envoyé
	    </div>
	  </div>
	</div>
</div>
 -->

<section  class="container container-website col-lg-10 col-lg-offset-1">
	<div class="black-box col-lg-10 col-lg-offset-1">
		<div class="rub">
			<h3 class="col-lg-12 title-rub">CONTACTEZ-NOUS</h3>
		</div>
	</div>
	<div class="col-lg-10 col-lg-offset-1" style="width: 89%; margin-left: 62px;  margin-top: 20px;">
		<form id="contact-form" class="form-contact" enctype="multipart/form-data">
	        <span class="col-lg-6">
	        	<p>VOTRE NOM *</p>
	        	<input type="text" id="nom" name="name" >
	        </span>
	        <span class="col-lg-6">
	        	<p>VOTRE EMAIL *</p>
	        	<input type="text" id="mail" name="email">
	        </span>
	        <span class="col-lg-6">
	        	<p>SUJET *</p>
	        	<input type="text" id="nom" name="name" >
	        </span>
	        <span class="col-lg-6">
	        	<p>VOTRE NUMERO DU TELEPHONE *</p>
	        	<input type="text" id="mail" name="email">
	        </span>
	        <span class="col-lg-12">
	        	<p>VOTRE MESSAGE *</p>
	        	<textarea rows="10" name="message"></textarea>
	        </span>
	        <span class="col-lg-12" style="margin-bottom: 60px;">
				<span class="col-lg-4  col-md-4 col-lg-offset-4 col-md-offset-4" ><input type="submit" id="submit" value="ENVOYER" /></span>
			</span>
    	</form>
	</div>
</section>